export enum Sintoma {
  ARDOR = 'ARDOR',
  HORMIGUEO = 'HORMIGUEO',
  INFLAMACION = 'INFLAMACION',
  RIGIDEZ = 'RIGIDEZ',
  DOLOR = 'DOLOR',
  SENSIBILIDA_TACTO = 'SENSIBILIDA_TACTO',
  DEBILIDAD = 'DEBILIDAD',
  DIFICULTADAD_MOVIMIENTO = 'DIFICULTADAD_MOVIMIENTO',
}
