export enum Tipo_Zona{
    CABEZA= "CABEZA",
    PECHO= "PECHO",
    PIERNAS= "PIERNAS",
    BRAZOS = "BRAZOS",
    MANOS= "MANOS",
    PIES= "PIES",
    ESTOMAGO= "ESTOMAGO",
    PARTES_INTIMAS= "PARTES_INTIMAS"
}